// <auto-generated />
namespace TaskAionys.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Client_Task_1toN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Client_Task_1toN));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201840010_Client_Task_1toN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
